const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"荣誉信息",
                        "menuJump":"列表",
                        "tableName":"rongyu"
                    }
                ],
                "menu":"全部荣誉信息"
            }
			,
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"学生成果",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生成果"
			},
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"我发布的荣誉信息",
                        "menuJump":"列表",
                        "tableName":"rongyuList"
                    }
                ],
                "menu":"我发布的荣誉信息"
            },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"我发布的学生成果",
			            "menuJump":"列表",
			            "tableName":"yonghuList"
			        }
			    ],
			    "menu":"我发布的学生成果"
			}
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"教师",
        "tableName":"jiaoshi"
    }
]

	}
}
export default menu;
